insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Xavier''s School for Gifted Youngsters',0.39);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Acme Corporation',0.14);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Cyberdyne Systems Corporation',0.1);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Nergal Heavy Industries',0.375);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'InGen',0.265);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Joe''s Diner',0.29);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Queen Industries',0.205);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Wayne Enterprises',0.44);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Yoyodyne Propulsion Systems',0.275);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Magic Box, The',0.205);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Vaillante',0.3);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Sirius Cybernetics Corporation',0.12);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Duff Beer',0.065);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Tyrell Corporation',0.04);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Ewing Oil',0.305);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Fantastic Enterprises',0.095);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Golden Goblin Press',0.015);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Kwik-E-Mart',0.305);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Omni Consumer Products',0.26);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Bonk Business',0.115);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'LexCorp',0.355);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Ziktor Industries',0.47);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Phua Chu Kang',0.43);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Halo Corporation',0.5);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'Roxxon Energy Corporation',0.035);
insert into CUSTOMER (VERSION,NAME,DISCOUNT) values (0,'U.S. Robots and Mechanical Men',0.07);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'First Aid Kit','HZO-1200',3.26);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'X-ray Scanner','BMY-1080',5775);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Ballpoint Pens','XTE-1283',0.46);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Hanging Folders','EMJ-6236',61.2);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Comfy Chair','IFK-7717',673.5);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Uninterruptible Power Supply','ZIZ-7901',6515);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Inkjet Printer Paper','YNW-8393',73);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Dilithium Crystals','MCJ-9513',1160);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Red Swingline Stapler','TAE-9069',86);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Adhesive Tape','GQL-2607',7.13);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Pocket Protector','KWA-2100',0.79);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Yellow Highlighter','ECV-9028',0.85);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Grey Filing Cabinet','COB-6406',682);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Java Tutorial','YJN-8549',51.8);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Krazy Glue','YVQ-4208',0.2);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Zero Point Module','CXE-6767',6455);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Ergonomic Keyboard','ZFE-8617',77.15);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Legal Pad','TLF-2193',3.98);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Vanilla Folders','RTE-6445',41.85);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Number 2 Pencils','MFT-7841',0.01);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Metal Ruler','DUS-2245',0.52);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Whiteboard','HOB-7634',705.5);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Three Ring Binder','SEE-6844',7.12);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Overhead Projector','DPK-6043',604);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Spiral Notebook','OGN-9733',4.35);
insert into ITEM (VERSION,DESCRIPTION,SKU,UNIT_PRICE) values (0,'Quick Dry Cement','DNE-6494',567.5);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Vaillante'),{d '2011-9-7'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),756);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),339);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),9);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),63);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),154);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),243);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),10);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Golden Goblin Press'),{d '2010-6-14'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),144);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),205);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),12);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Nergal Heavy Industries'),{d '2010-10-25'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),10);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),44);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),47);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),13);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),14);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),12);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Queen Industries'),{d '2011-2-23'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),68);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),9);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),25);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),71);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),41);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),822);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),193);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),193);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),9);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),60);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),13);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),122);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),809);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Tyrell Corporation'),{d '2011-7-17'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),120);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),14);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),67);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),122);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),141);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),60);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),61);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),7);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),26);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Nergal Heavy Industries'),{d '2011-4-22'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),63);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),305);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),235);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),21);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),160);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),16);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Cyberdyne Systems Corporation'),{d '2011-12-15'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),17);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),219);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),53);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),45);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),241);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),48);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Xavier''s School for Gifted Youngsters'),{d '2010-2-9'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),153);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),47);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),137);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),10);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),21);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Bonk Business'),{d '2010-1-20'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),9);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),13);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),63);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),4);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Xavier''s School for Gifted Youngsters'),{d '2011-9-8'},'CANCELED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),666);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Yoyodyne Propulsion Systems'),{d '2010-3-5'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),14);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),436);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),72);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),53);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),197);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Queen Industries'),{d '2010-4-21'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),62);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),8);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),28);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),8);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),97);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),18);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Roxxon Energy Corporation'),{d '2010-8-17'},'CANCELED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),34);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),19);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),229);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),35);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),94);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),267);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),229);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),899);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),26);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),63);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),22);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Tyrell Corporation'),{d '2012-2-17'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),31);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),30);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),180);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),17);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Cyberdyne Systems Corporation'),{d '2011-4-8'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),9);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),15);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),43);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),66);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),204);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Bonk Business'),{d '2012-2-24'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),39);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),63);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),13);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),7);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),23);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Yoyodyne Propulsion Systems'),{d '2010-1-23'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),157);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),12);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),12);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),207);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),7);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),39);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),235);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),47);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),10);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),114);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Ewing Oil'),{d '2011-11-9'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),220);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),224);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),209);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),93);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),17);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),56);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),38);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Ziktor Industries'),{d '2010-7-12'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),227);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),64);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),247);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),56);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TAE-9069'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),79);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),237);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),19);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Magic Box, The'),{d '2010-12-30'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),29);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),72);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),25);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='COB-6406'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),13);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),165);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),228);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),28);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),2);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Bonk Business'),{d '2011-6-19'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),235);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),10);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),111);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),21);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),14);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),969);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZIZ-7901'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),780);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Joe''s Diner'),{d '2010-12-12'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),54);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ZFE-8617'),11);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),110);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),45);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),19);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),82);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),181);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YJN-8549'),14);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),1021);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),18);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),4);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Golden Goblin Press'),{d '2010-9-18'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='BMY-1080'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),58);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),3);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),6);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),96);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),58);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),16);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Wayne Enterprises'),{d '2012-1-29'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MFT-7841'),1009);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='XTE-1283'),75);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),61);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),8);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),56);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YNW-8393'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),119);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),118);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DNE-6494'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),31);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),97);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='GQL-2607'),21);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Halo Corporation'),{d '2011-10-19'},'SHIPPED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='KWA-2100'),41);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),28);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='CXE-6767'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),219);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),250);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='RTE-6445'),5);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='TLF-2193'),27);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),7);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HOB-7634'),2);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='IFK-7717'),2);
insert into ORDER_HEADER (VERSION,CUSTOMER_ID,ENTRY_DATE,ORDER_STATUS) values (0,(select ID from CUSTOMER where NAME='Golden Goblin Press'),{d '2011-6-7'},'ENTERED');
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='SEE-6844'),19);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),93);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='YVQ-4208'),31);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='ECV-9028'),240);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DPK-6043'),4);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='DUS-2245'),105);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='OGN-9733'),53);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='EMJ-6236'),8);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='HZO-1200'),35);
insert into ORDER_LINE (VERSION,ORDER_ID,ITEM_ID,QUANTITY) values (0,(select max(ID) from ORDER_HEADER),(select ID from ITEM where SKU='MCJ-9513'),1);